# code: language=ansible
---
- name: 'Set fregments in zshrc file for user: {{ user.name }}'
  ansible.builtin.blockinfile:
    path: '~{{ user.name }}/.zshrc'
    block: "{{ user.zshrc_fregments | join('\n') }}"
