# code: language=ansible
---
- name: Clone custom plugins (skipped if using builtin plugin)
  become: true
  become_user: '{{ user.name }}'
  ansible.builtin.git:
    repo: '{{ plugin.repo }}'
    dest: '~{{ user.name }}/.oh-my-zsh/custom/plugins/{{ plugin.name }}'
    depth: 1
    version: '{{ plugin.revision }}'
  loop: '{{ plugins | flatten(levels=1) }}'
  loop_control:
    loop_var: plugin
    label: '{{ plugin.name }}'
  when: 'plugin.name in (user.activate.plugins)'

- name: 'Set plugins for user: {{ user.name }}'
  become: true
  become_user: '{{ user.name }}'
  ansible.builtin.lineinfile:
    path: '~{{ user.name }}/.zshrc'
    regexp: |- 
      ^plugins=
    line: "plugins=({{ user.activate.plugins | join(' ') }})"
