# code: language=ansible
---
- name: Set merged_scripts list
  ansible.builtin.set_fact:
    merged_scripts: >-
      {{ (oh_my_zsh.scripts | default(oh_my_zsh_scripts) | list) | community.general.lists_mergeby(
                    scripts,
                    'name',
                    recursive=True,
                    list_merge='replace'
                 ) }}

- name: 'Ensure directory exists: {{ script.path }}'
  become: true
  become_user: '{{ user.name }}'
  ansible.builtin.file:
    path: '~{{ user.name }}/{{ script.path }}'
    state: directory
    mode: '0755'
  loop: '{{ merged_scripts }}'
  loop_control:
    loop_var: script
    label: '~{{ user.name }}/{{ script.path }}'
  when: script.path is defined and script.content is defined and script.mode is defined

- name: 'Create custom scripts'
  become: true
  ansible.builtin.copy:
    content: '{{ script.content }}'
    dest: '~{{ user.name }}/{{ script.path }}/{{ script.name }}'
    mode: '{{ script.mode }}'
    owner: '{{ user.name }}'
    group: '{{ user.name }}'
  loop: '{{ merged_scripts }}'
  loop_control:
    loop_var: script
    label: '{{ script.name }}'
  when: script.path is defined and script.content is defined and script.mode is defined
